apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  namespace: scaletest
  labels:
    app: scaletestapp
spec:
  type: ClusterIP
  selector:
    app: scaletestapp
  ports:
    - name: http
      port: 8080
      targetPort: http

