@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(покупатель, "Покупатель", "Веб?")

System_Boundary(novamarket, "NovaMarket") {

    Container(nginx, "NGINX", "API Gateway")
    Container(metrics, "Метрики", "Prometheus/Grafana", "Сбор и визуализация метрик")
    Container(auth, "Сервис аутенфикации", "Spring Boot", "Аутенфикация/JWT")
    Container(catalog, "Сервис обработки каталога", "Spring Boot", "Меню товаров с фильтрацией")
    Container(review, "Сервис отзывов", "Spring Boot", "Рейтинги, отзывы и т.д")
    Container(cart, "Сервис корзины", "Spring Boot", "Корзина пользователя")
    Container(order, "Сервис заказов", "Spring Boot", "Заказы")

    Container(invent, "Сервис инвентаризации", "Spring Boot", "Проверка наличия, резервирование")
    Container(payment, "Платжный сервис", "Spring Boot", "Платежи")
    Container(delivery, "Сервис логистики", "Spring Boot", "Формирование заявки на доставку")
    Container(notification, "Сервис уведомлений", "Spring Boot", "Уведомления")
    Container(seller_service, "Сервис продавцов", "Spring Boot", "ЛК продавца")

    Container(kafka, "Kafka", "Apache Kafka", "Брокер сообщений")
}

Rel(покупатель, nginx, "use")

Rel_L(metrics, nginx, "")
Rel(metrics, review, "")
Rel(metrics, order, "")
Rel(metrics, invent, "")
Rel(metrics, delivery, "")
Rel(metrics, kafka, "")
Rel(metrics, auth, "")
Rel(metrics, catalog, "")
Rel(metrics, cart, "")
Rel(metrics, payment, "")

Rel(nginx, auth, "REST API")
Rel(nginx, catalog, "REST API")
Rel(nginx, review, "REST API")
Rel(nginx, cart, "REST API")
Rel(nginx, order, "REST API")

Rel(order, kafka, "Продюсер")
Rel(invent, kafka, "Консьюмер/Продюсер")
Rel(payment, kafka, "Консьюмер/Продюсер")
Rel(delivery, kafka, "Консьюмер/Продюсер")
Rel(notification, kafka, "Консьюмер")
Rel(seller_service, kafka, "Консьюмер")

@enduml